M48
; DRILL file {KiCad 9.0.1} date 2025-12-21T14:23:17+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-21T14:23:17+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X103.632Y-77.216
X103.632Y-105.41
X152.146Y-77.216
X152.146Y-105.41
M30
